package com.simplicityapp.base.analytics

import com.simplicityapp.base.data.ThisApplication

class AnalyticsConstants {

    companion object {
        /**
         * --------------------------------Analytics Events-------------------------------------------
         */

        const val TERMS_AND_CONDITIONS_PREVIOUS = "TERMS_AND_CONDITIONS_PREVIOUS"
        const val TERMS_AND_CONDITIONS_SUCCESS = "TERMS_AND_CONDITIONS_SUCCESS"

        const val LOGIN_SUCCESS = "LOGIN_SUCCESS"

        const val VIEW_PLACE = "VIEW_PLACE"
        const val VIEW_NOTIFICATION = "VIEW_NOTIFICATION"

        const val SELECT_HOME_FAB_MAP = "SELECT_HOME_FAB_MAP"
        const val SELECT_HOME_FAB_SEARCH = "SELECT_HOME_FAB_SEARCH"
        const val SELECT_HOME_FAB_FAVORITES = "SELECT_HOME_FAB_FAVORITES"
        const val SELECT_HOME_SHARE_APP = "SELECT_HOME_SHARE_APP"
        const val SELECT_HOME_OPEN_REGISTER_FORM = "SELECT_HOME_OPEN_REGISTER_FORM"
        const val SELECT_HOME_REFRESH = "SELECT_HOME_REFRESH"

        const val SELECT_HOME_FEATURED_BANNER = "SELECT_HOME_FEATURED_BANNER"

        const val SELECT_TOOLBAR_SETTINGS = "SELECT_TOOLBAR_SETTINGS"
        const val SELECT_TOOLBAR_RATE = "SELECT_TOOLBAR_RATE"
        const val SELECT_TOOLBAR_ABOUT = "SELECT_TOOLBAR_ABOUT"

        const val SELECT_MENU_HOME = "SELECT_MENU_HOME"
        const val SELECT_MENU_ALL_PLACES = "SELECT_MENU_ALL_PLACES"
        const val SELECT_MENU_MAP = "SELECT_MENU_MAP"
        const val SELECT_MENU_SEARCH = "SELECT_MENU_SEARCH"
        const val SELECT_MENU_FAVORITES = "SELECT_MENU_FAVORITES"
        const val SELECT_MENU_NOTIFICATIONS = "SELECT_MENU_NOTIFICATIONS"

        const val SELECT_MENU_CATEGORY_FEATURED = "SELECT_MENU_CATEGORY_FEATURED"
        const val SELECT_MENU_CATEGORY_STORE = "SELECT_MENU_CATEGORY_STORE"
        const val SELECT_MENU_CATEGORY_DELIVERY = "SELECT_MENU_CATEGORY_DELIVERY"
        const val SELECT_MENU_CATEGORY_FAST_FOOD = "SELECT_MENU_CATEGORY_FAST_FOOD"
        const val SELECT_MENU_CATEGORY_RESTAURANTS = "SELECT_MENU_CATEGORY_RESTAURANTS"
        const val SELECT_MENU_CATEGORY_BAR = "SELECT_MENU_CATEGORY_BAR"
        const val SELECT_MENU_CATEGORY_ICE_CREAM = "SELECT_MENU_CATEGORY_ICE_CREAM"
        const val SELECT_MENU_CATEGORY_GYM_CENTER = "SELECT_MENU_CATEGORY_GYM_CENTER"
        const val SELECT_MENU_CATEGORY_CLOTHING_STORES = "SELECT_MENU_CATEGORY_CLOTHING_STORES"
        const val SELECT_MENU_CATEGORY_BIG_STORES = "SELECT_MENU_CATEGORY_BIG_STORES"
        const val SELECT_MENU_CATEGORY_INDUSTRIAL_STORES = "SELECT_MENU_CATEGORY_INDUSTRIAL_STORES"
        const val SELECT_MENU_CATEGORY_BILL_PAYMENTS = "SELECT_MENU_CATEGORY_BILL_PAYMENTS"
        const val SELECT_MENU_CATEGORY_ART = "SELECT_MENU_CATEGORY_ART"
        const val SELECT_MENU_CATEGORY_JOBS = "SELECT_MENU_CATEGORY_JOBS"
        const val SELECT_MENU_CATEGORY_MONEY = "SELECT_MENU_CATEGORY_MONEY"
        const val SELECT_MENU_CATEGORY_TOURIST_DESTINATION = "SELECT_MENU_CATEGORY_TOURIST_DESTINATION"
        const val SELECT_MENU_CATEGORY_HOTEL = "SELECT_MENU_CATEGORY_HOTEL"
        const val SELECT_MENU_CATEGORY_APARTMENT_RENTAL = "SELECT_MENU_CATEGORY_APARTMENT_RENTAL"
        const val SELECT_MENU_CATEGORY_TEMPORARY_RENT = "SELECT_MENU_CATEGORY_TEMPORARY_RENT"
        const val SELECT_MENU_CATEGORY_TAXI = "SELECT_MENU_CATEGORY_TAXI"
        const val SELECT_MENU_CATEGORY_GAS_STATION = "SELECT_MENU_CATEGORY_GAS_STATION"
        const val SELECT_MENU_CATEGORY_TRANSPORT = "SELECT_MENU_CATEGORY_TRANSPORT"
        const val SELECT_MENU_CATEGORY_TRANSPORT_TICKETS = "SELECT_MENU_CATEGORY_TRANSPORT_TICKETS"
        const val SELECT_MENU_CATEGORY_PHARMACY = "SELECT_MENU_CATEGORY_PHARMACY"
        const val SELECT_MENU_CATEGORY_EMERGENCIES = "SELECT_MENU_CATEGORY_EMERGENCIES"

        const val SELECT_MENU_OPEN_REGISTER_FORM = "SELECT_MENU_OPEN_REGISTER_FORM"
        const val SELECT_MENU_OPEN_SUGGESTION_FORM = "SELECT_MENU_OPEN_SUGGESTION_FORM"
        const val SELECT_MENU_OPEN_GET_IN_TOUCH = "SELECT_MENU_OPEN_GET_IN_TOUCH"
        const val SELECT_MENU_OPEN_SETTINGS = "SELECT_MENU_OPEN_SETTINGS"

        const val SELECT_PLACE_ADDRESS = "SELECT_PLACE_ADDRESS"
        const val SELECT_PLACE_PHONE = "SELECT_PLACE_PHONE"
        const val SELECT_PLACE_WEB_SITE = "SELECT_PLACE_WEB_SITE"
        const val SELECT_PLACE_PHOTO = "SELECT_PLACE_PHOTO"
        const val SELECT_PLACE_DESCRIPTION_CONTENT = "SELECT_PLACE_DESCRIPTION_CONTENT"
        const val SELECT_PLACE_OPEN_MAP = "SELECT_PLACE_OPEN_MAP"
        const val SELECT_PLACE_OPEN_NAVIGATION = "SELECT_PLACE_OPEN_NAVIGATION"
        const val SELECT_PLACE_SHARE = "SELECT_PLACE_SHARE"
        const val SELECT_PLACE_FAVORITES_ADD = "SELECT_PLACE_FAVORITES_ADD"
        const val SELECT_PLACE_FAVORITES_REMOVE = "SELECT_PLACE_FAVORITES_REMOVE"

        const val SELECT_NOTIFICATIONS_LIST_REFRESH = "SELECT_NOTIFICATIONS_LIST_REFRESH"
        const val SELECT_NOTIFICATIONS_LIST_OPEN_ITEM = "SELECT_NOTIFICATIONS_LIST_OPEN_ITEM"

        const val SELECT_NOTIFICATION_ITEM_SHARE = "SELECT_NOTIFICATION_ITEM_SHARE"
        const val SELECT_NOTIFICATION_OPEN_PHOTO = "SELECT_NOTIFICATION_OPEN_PHOTO"

        const val SELECT_MAP_CATEGORY = "SELECT_MAP_CATEGORY"
        const val SELECT_MAP_PLACE = "SELECT_MAP_PLACE"

        const val SEARCH_PLACE = "SEARCH_PLACE"
        const val SELECT_SEARCHED_PLACE = "SELECT_SEARCHED_PLACE"

        const val SELECT_CATEGORY_PLACE = "SELECT_CATEGORY_PLACE"

        /**
         * --------------------------------Analytics Params----------------------------------------
         */
        const val FIRST_RUN = "FIRST_RUN"
        const val NORMAL_RUN = "NORMAL_RUN"
        const val UPGRADE_RUN = "UPGRADE_RUN"

        /**
         * --------------------------------Analytics Methods----------------------------------------
         */

        fun logAnalyticsEvent(event: String, label: String? = null, user: Boolean? = null, fullUser: Boolean? = null) {
            ThisApplication.instance?.trackEvent(event, label,  user, fullUser)
        }
    }



}